<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<HTML>
<HEAD>

<!-- Generated by ${build.version} on ${build.date} -->
<TITLE>
Zimbra SOAP API Reference ${build.version}
</TITLE>
<SCRIPT type="text/javascript">
   targetPage = "" + window.location.search;
   if (targetPage != "" && targetPage != "undefined")
      targetPage = targetPage.substring(1);
   if (targetPage.indexOf(":") != -1)
      targetPage = "undefined";
   function loadFrames() {
      if (targetPage != "" && targetPage != "undefined")
	  top.classFrame.location = top.targetPage;
     }
</SCRIPT>
</HEAD>
<FRAMESET cols="20%,80%" title="" onLoad="top.loadFrames()">
<FRAMESET rows="30%,70%" title="" onLoad="top.loadFrames()">
<FRAME src="overview-frame.html" name="serviceListFrame" title="All Commands">

<FRAME src="allcommands-frame.html" name="serviceFrame" title="All Commands">
</FRAMESET>
<FRAME src="overview-summary.html" name="commandFrame" title="Service and command descriptions" scrolling="yes">
<NOFRAMES>
<H2>Frame Alert</H2>

<P>
This document is designed to be viewed using the frames feature. If you see this message, you are using a non-frame-capable web client.
<BR>
</NOFRAMES>
</FRAMESET>
</HTML>
