/* Generated By:JavaCC: Do not edit this line. ZimbraQueryParserConstants.java */
package com.zimbra.cs.index.queryparser;

public interface ZimbraQueryParserConstants {

  int EOF = 0;
  int AND_TOKEN = 5;
  int OR_TOKEN = 6;
  int NOT_TOKEN = 7;
  int LPAREN = 8;
  int RPAREN = 9;
  int CONTENT = 10;
  int SUBJECT = 11;
  int MSGID = 12;
  int ENVTO = 13;
  int ENVFROM = 14;
  int CONTACT = 15;
  int TO = 16;
  int FROM = 17;
  int CC = 18;
  int TOFROM = 19;
  int TOCC = 20;
  int FROMCC = 21;
  int TOFROMCC = 22;
  int IN = 23;
  int UNDER = 24;
  int INID = 25;
  int UNDERID = 26;
  int HAS = 27;
  int FILENAME = 28;
  int TYPE = 29;
  int ATTACHMENT = 30;
  int IS = 31;
  int DATE = 32;
  int DAY = 33;
  int WEEK = 34;
  int MONTH = 35;
  int YEAR = 36;
  int AFTER = 37;
  int BEFORE = 38;
  int SIZE = 39;
  int BIGGER = 40;
  int BIGGER_STR = 41;
  int LARGER = 42;
  int SMALLER = 43;
  int TAG = 44;
  int MESSAGE = 45;
  int MY = 46;
  int MODSEQ = 47;
  int CONV = 48;
  int CONV_COUNT = 49;
  int CONV_MINM = 50;
  int CONV_MAXM = 51;
  int CONV_START = 52;
  int CONV_END = 53;
  int APPT_START = 54;
  int APPT_END = 55;
  int AUTHOR = 56;
  int TITLE = 57;
  int KEYWORDS = 58;
  int COMPANY = 59;
  int METADATA = 60;
  int ITEM = 61;
  int SORTBY = 62;
  int SORT = 63;
  int PLUS = 64;
  int MINUS = 65;
  int TEXT_TOK = 66;
  int INITIAL_TERM_CHAR = 67;
  int SUBSEQUENT_TERM_CHAR = 68;
  int ERROR_BRACES_WITH_NEWLINE = 70;
  int BRACES_TOK = 71;
  int ERROR_QUOTE_WITH_NEWLINE = 73;
  int QUOTED_TOK = 74;

  int DEFAULT = 0;
  int BRACES_STATE = 1;
  int QUOTED_STATE = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"{\"",
    "\"\\\"\"",
    "<AND_TOKEN>",
    "<OR_TOKEN>",
    "<NOT_TOKEN>",
    "\"(\"",
    "\")\"",
    "\"content:\"",
    "\"subject:\"",
    "\"msgid:\"",
    "\"envto:\"",
    "\"envfrom:\"",
    "\"contact:\"",
    "\"to:\"",
    "\"from:\"",
    "\"cc:\"",
    "\"tofrom:\"",
    "\"tocc:\"",
    "\"fromcc:\"",
    "\"tofromcc:\"",
    "\"in:\"",
    "\"under:\"",
    "\"inid:\"",
    "\"underid:\"",
    "\"has:\"",
    "\"filename:\"",
    "\"type:\"",
    "\"attachment:\"",
    "\"is:\"",
    "\"date:\"",
    "\"day:\"",
    "\"week:\"",
    "\"month:\"",
    "\"year:\"",
    "\"after:\"",
    "\"before:\"",
    "\"size:\"",
    "<BIGGER>",
    "\"bigger:\"",
    "\"larger:\"",
    "\"smaller:\"",
    "\"tag:\"",
    "\"message:\"",
    "\"my:\"",
    "\"modseq:\"",
    "\"conv:\"",
    "\"conv-count:\"",
    "\"conv-minm:\"",
    "\"conv-maxm:\"",
    "\"conv-start:\"",
    "\"conv-end:\"",
    "\"appt-start:\"",
    "\"appt-end:\"",
    "\"author:\"",
    "\"title:\"",
    "\"keywords:\"",
    "\"company:\"",
    "\"metadata:\"",
    "\"item:\"",
    "\"sortby:\"",
    "\"sort:\"",
    "\"+\"",
    "\"-\"",
    "<TEXT_TOK>",
    "<INITIAL_TERM_CHAR>",
    "<SUBSEQUENT_TERM_CHAR>",
    "\"}\"",
    "<ERROR_BRACES_WITH_NEWLINE>",
    "<BRACES_TOK>",
    "\"\\\"\"",
    "<ERROR_QUOTE_WITH_NEWLINE>",
    "<QUOTED_TOK>",
    "\"\\r\"",
  };

}
