<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>

<!-- Generated by ${build.version} on ${build.date} -->
<title>
Zimbra SOAP API Reference ${build.version}
</title>

<LINK REL ="stylesheet" TYPE="text/css" HREF="stylesheet.css" TITLE="Style">

<script type="text/javascript">
function windowTitle()
{
    parent.document.title="Zimbra SOAP API Reference ${build.version}";
}
</script>

</head>

<body bgcolor="white" onload="windowTitle();">

<table cellspacing="3" cellpadding="0" border="0" summary="" bgcolor="#eeeeff">
  <tbody>
  <tr valign="top" align="center">
  <td bgcolor="#eeeeff" class="NavBarCell1Rev">    &nbsp;<font class="NavBarFont1Rev"><b>Overview</b></font>&nbsp;</td>
  <td bgcolor="#ffffff" class="NavBarCell1"> <font class="NavBarFont1">Service</font>&nbsp;</td>
  <td bgcolor="#eeeeff" class="NavBarCell1">    <font class="NavBarFont1">Command</font>&nbsp;</td>
  </tr>
  </tbody>
</table>

<hr>
<center>
<h1>
Zimbra<sup><font size=-2>TM</font></sup> SOAP API Reference ${build.version}
</h1>
</center>
This document is the reference specification for the Zimbra SOAP API.

<p>

<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="2"><FONT SIZE="+2">
<B>SOAP API Services</B></FONT></TH>
</TR>
<#list root.services as service>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD WIDTH="20%"><B><A HREF="./${service.name}/service-summary.html">${service.name}</A></B></TD>
<TD>${service.description}</TD>
</TR>
</#list>
</TABLE>

<HR>
<p>
Copyright 2023 Synacor, Inc. All rights reserved.
</p>

</body>
</html>
