<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>

<!-- Generated by ${build.version} on ${build.date} -->
<title>
Zimbra SOAP API Reference ${build.version}
</title>

<LINK REL ="stylesheet" TYPE="text/css" HREF="../stylesheet.css" TITLE="Style">

<script type="text/javascript">
function windowTitle()
{
    parent.document.title="Command <${command.requestName}> (Zimbra SOAP API Reference ${build.version})";
}
</script>

</head>

<body BGCOLOR="white" onload="windowTitle();">

<table cellspacing="3" cellpadding="0" border="0" summary="" bgcolor="#eeeeff">
  <tbody>
  <tr valign="top" align="center">
  <td bgcolor="#ffffff" class="NavBarCell1"> <a href="../overview-summary.html"><font class="NavBarFont1"><b>Overview</b></font></a>&nbsp;</td>
  <td bgcolor="#eeeeff" class="NavBarCell1">    <a href="./service-summary.html"><font class="NavBarFont1"><b>Service</b></font></a>&nbsp;</td>
  <td bgcolor="#eeeeff" class="NavBarCell1Rev">    &nbsp;<font class="NavBarFont1Rev"><b>Command</b></font>&nbsp;</td>
  </tr>
  </tbody>
</table>

<hr>
<h2>
<font SIZE="-1"><a href="./service-summary.html">Service: ${service.name}</a></font>
<br>
<font SIZE="-1">Namespace: "${command.namespace}"</font>
<br>
${command.name} SOAP Command</h2>
<#if command.hasDeprecationDescription()>
<p>
<b>${command.deprecation}</b>
</p>
</#if>
<#if command.isNetworkEdition()>
<p>
This is a <b>Network edition only</b> API
</p>
</#if>
<p>
${command.description}
</p>
<h2><a name="request">${command.requestName}</a></h2>
<#if command.request.description != "">
<p>
${command.request.description}
</p>
</#if>
<p>
${command.request.htmlDescription}
</p>
<#if command.request.childDocumentableXmlUnits?size != 0>
<p>
The following table describes elements and attributes you can define within a
<code>&lt;${command.requestName}&gt;</code> element:
</p>
<table cellspacing="0" cellpadding="5" border="1" width="100%">
<tbody>
    <tr BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
        <td width="1%" nowrap><b>XPath</b></td>
        <td width="1%" nowrap><b>Required / Optional</b></td>
        <td><b>Description</b></td>
    </tr>
<#list command.request.childDocumentableXmlUnits as unit>
    <tr>
        <td><a href="#request-${unit.name}">${unit.XPath}</a></td>
        <td>
        <#switch unit.occurrence>
              <#case "REQUIRED">
              Required (only 1)
              <#break>
              <#case "OPTIONAL">
              Optional (0 or 1)
              <#break>
              <#case "REQUIRED_MORE">
              Required (1 or more)
              <#break>
              <#case "OPTIONAL_MORE">
              Optional (0 or more)
              <#break>
        </#switch>
        </td>
        <td>${unit.description}</td>
    </tr>
</#list>
</tbody>
</table>
</#if>

<h2><a name="response">${command.responseName}</a></h2>
<#if command.response.description != "">
<p>
${command.response.description}
</p>
</#if>
<p>
${command.response.htmlDescription}
</p>
<#if command.response.childDocumentableXmlUnits?size != 0>
<p>
The following table describes elements and attributes you can define within a
<code>&lt;${command.responseName}&gt;</code> element:
</p>
<table cellspacing="0" cellpadding="5" border="1" width="100%">
<tbody>
    <tr BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
        <td width="1%" nowrap><b>XPath</b></td>
        <td width="1%" nowrap><b>Required / Optional</b></td>
        <td><b>Description</b></td>
    </tr>
<#list command.response.childDocumentableXmlUnits as unit>
    <tr>
        <td><a href="#response-${unit.name}">${unit.XPath}</a></td>
        <td>
        <#switch unit.occurrence>
              <#case "REQUIRED">
              Required (only 1)
              <#break>
              <#case "OPTIONAL">
              Optional (0 or 1)
              <#break>
              <#case "REQUIRED_MORE">
              Required (1 or more)
              <#break>
              <#case "OPTIONAL_MORE">
              Optional (0 or more)
              <#break>
        </#switch>
        </td>
        <td>${unit.description}</td>
    </tr>
</#list>
</tbody>
</table>
</#if>
</body>
</html>
