<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>

<!-- Generated by ${build.version} on ${build.date} -->
<TITLE>
${service.name} (Zimbra SOAP API Reference ${build.version})
</TITLE>

<LINK REL ="stylesheet" TYPE="text/css" HREF="../stylesheet.css" TITLE="Style">


</HEAD>

<BODY BGCOLOR="white">
<FONT size="+1" CLASS="FrameTitleFont">
<A HREF="./service-summary.html" target="commandFrame">${service.name}</A></FONT>
<TABLE BORDER="0" WIDTH="100%" SUMMARY="">
<TR>
<TD NOWRAP><FONT size="+1" CLASS="FrameHeadingFont">Commands</FONT>&nbsp;
<FONT CLASS="FrameItemFont">
<#list service.commands as command>
<BR>
<A HREF="${command.name}.html" title="command in ${command.service.name}" target="commandFrame">${command.name}</A>
</#list>
</FONT>
</TR>
</TABLE>

</BODY>
</HTML>
