Return-Path: user1@cosmonaut.zimbra.com
Received: from localhost (LHLO cosmonaut.zimbra.com) (127.0.0.1) by
 cosmonaut.zimbra.com with LMTP; Wed, 15 Oct 2008 16:52:15 -0700 (PDT)
Date: Wed, 15 Oct 2008 16:52:15 -0700 (PDT)
From: Demo User One <"user\\1"@cosmonaut.zimbra.com>
To: user1 <user.1@cosmonaut.zimbra.com>
Subject: TestFilter testBodyContains
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_5_31675071.1224114735321"
X-Mailer: Zimbra 5.0 (ZimbraWebClient - FF3.0 (Linux)/0.0)

------=_Part_5_31675071.1224114735321
Content-Type: multipart/alternative; 
	boundary="----=_Part_6_21859329.1224114735321"

------=_Part_6_21859329.1224114735321
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

This is the text version of the main body of the message.
This is the second line.

------=_Part_6_21859329.1224114735321
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html><head><style type='text/css'>p { margin: 0; }</style></head><body><div style='font-family: Times New Roman; font-size: 12pt; color: #000000'>This is the HTML<br>
version of the main body of the message.<br></div></body></html>
------=_Part_6_21859329.1224114735321--

------=_Part_5_31675071.1224114735321
Content-Type: text/html; name=attachment.html
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename=attachment.html

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <meta content="text/html; charset=ISO-8859-1"
 http-equiv="content-type">
  <title>HTML attachment</title>
</head>
<body>
This is an HTML attachment.
</body>
</html>

------=_Part_5_31675071.1224114735321
Content-Type: text/plain; name=attachment.txt
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename=attachment.txt

This is a text attachment.


------=_Part_5_31675071.1224114735321
Content-Type: message/rfc822
Content-Disposition: attachment

Return-Path: user1@cosmonaut.zimbra.com
Received: from localhost (LHLO cosmonaut.zimbra.com) (127.0.0.1) by
 cosmonaut.zimbra.com with LMTP; Wed, 15 Oct 2008 16:45:36 -0700 (PDT)
Date: Wed, 15 Oct 2008 16:45:36 -0700 (PDT)
From: Demo User One <user1@cosmonaut.zimbra.com>
To: user1 <user1@cosmonaut.zimbra.com>
Message-ID: <964414.01224114336185.JavaMail.boris@cosmonaut>
Subject: Attached HTML message
MIME-Version: 1.0
Content-Type: multipart/alternative; 
	boundary="----=_Part_0_13178409.1224114336169"
X-Mailer: Zimbra 5.0 (ZimbraWebClient - FF3.0 (Linux)/0.0)

------=_Part_0_13178409.1224114336169
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit

This is the text version of the attached message body. 


------=_Part_0_13178409.1224114336169
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html><head><style type='text/css'>p { margin: 0; }</style></head><body><div style='font-family: Times New Roman; font-size: 12pt; color: #000000'>This is the HTML version the attached message body.<br><br></div></body></html>
------=_Part_0_13178409.1224114336169--

------=_Part_5_31675071.1224114735321
Content-Type: message/rfc822
Content-Disposition: attachment

Return-Path: user1@cosmonaut.zimbra.com
Received: from localhost (LHLO cosmonaut.zimbra.com) (127.0.0.1) by
 cosmonaut.zimbra.com with LMTP; Wed, 15 Oct 2008 14:25:21 -0700 (PDT)
Date: Wed, 15 Oct 2008 14:25:21 -0700 (PDT)
From: Demo User One <user1@cosmonaut.zimbra.com>
To: user1@cosmonaut.zimbra.com
Message-ID: <23494460.131224105921100.JavaMail.boris@cosmonaut>
Subject: Attached message
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
X-Mailer: Zimbra 5.0 (ZimbraWebClient - FF3.0 (Linux)/0.0)

This is the body of a plain attached message.

------=_Part_5_31675071.1224114735321--
