/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Server
 * Copyright (C) 2010, 2013 Zimbra Software, LLC.
 * 
 * The contents of this file are subject to the Zimbra Public License
 * Version 1.4 ("License"); you may not use this file except in
 * compliance with the License.  You may obtain a copy of the License at
 * http://www.zimbra.com/license.
 * 
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
 * ***** END LICENSE BLOCK *****
 */
/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package com.zimbra.cs.index.query.parser;

public interface ParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTQUERY = 1;
  public int JJTCLAUSE = 2;
  public int JJTDEFAULTCLAUSE = 3;
  public int JJTTEXTCLAUSE = 4;
  public int JJTITEMCLAUSE = 5;
  public int JJTDATECLAUSE = 6;
  public int JJTVOID = 7;
  public int JJTCONJUNCTION = 8;
  public int JJTMODIFIER = 9;
  public int JJTDATEMODIFIER = 10;
  public int JJTSORTBY = 11;
  public int JJTTEXTTERM = 12;
  public int JJTITEMTERM = 13;
  public int JJTDATETERM = 14;


  public String[] jjtNodeName = {
    "Root",
    "Query",
    "Clause",
    "DefaultClause",
    "TextClause",
    "ItemClause",
    "DateClause",
    "void",
    "Conjunction",
    "Modifier",
    "DateModifier",
    "SortBy",
    "TextTerm",
    "ItemTerm",
    "DateTerm",
  };
}
/* JavaCC - OriginalChecksum=948171b49488e41742c8291039f25b7c (do not edit this line) */
