/*
 * ***** BEGIN LICENSE BLOCK *****
 * Zimbra Collaboration Suite Server
 * Copyright (C) 2010, 2011, 2013, 2014 Zimbra, Inc.
 * 
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software Foundation,
 * version 2 of the License.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program.
 * If not, see <http://www.gnu.org/licenses/>.
 * ***** END LICENSE BLOCK *****
 */
/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package com.zimbra.cs.index.query.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 3;
  /** RegularExpression Id. */
  int RPAREN = 4;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int RANGE = 10;
  /** RegularExpression Id. */
  int TERM = 11;
  /** RegularExpression Id. */
  int _TERM_START_CHAR = 12;
  /** RegularExpression Id. */
  int _TERM_CHAR = 13;
  /** RegularExpression Id. */
  int QUOTED_TERM = 14;
  /** RegularExpression Id. */
  int _ESCAPED_QUOTE = 15;
  /** RegularExpression Id. */
  int BRACED_TERM = 16;
  /** RegularExpression Id. */
  int QUOTED_RANGE_TERM = 17;
  /** RegularExpression Id. */
  int CONTENT = 18;
  /** RegularExpression Id. */
  int SUBJECT = 19;
  /** RegularExpression Id. */
  int MSGID = 20;
  /** RegularExpression Id. */
  int ENVTO = 21;
  /** RegularExpression Id. */
  int ENVFROM = 22;
  /** RegularExpression Id. */
  int CONTACT = 23;
  /** RegularExpression Id. */
  int TO = 24;
  /** RegularExpression Id. */
  int FROM = 25;
  /** RegularExpression Id. */
  int CC = 26;
  /** RegularExpression Id. */
  int TOFROM = 27;
  /** RegularExpression Id. */
  int TOCC = 28;
  /** RegularExpression Id. */
  int FROMCC = 29;
  /** RegularExpression Id. */
  int TOFROMCC = 30;
  /** RegularExpression Id. */
  int FROMORSENDER = 31;
  /** RegularExpression Id. */
  int IN = 32;
  /** RegularExpression Id. */
  int UNDER = 33;
  /** RegularExpression Id. */
  int FILENAME = 34;
  /** RegularExpression Id. */
  int TAG = 35;
  /** RegularExpression Id. */
  int MESSAGE = 36;
  /** RegularExpression Id. */
  int MY = 37;
  /** RegularExpression Id. */
  int AUTHOR = 38;
  /** RegularExpression Id. */
  int TITLE = 39;
  /** RegularExpression Id. */
  int KEYWORDS = 40;
  /** RegularExpression Id. */
  int COMPANY = 41;
  /** RegularExpression Id. */
  int METADATA = 42;
  /** RegularExpression Id. */
  int FIELD = 43;
  /** RegularExpression Id. */
  int _FIELD1 = 44;
  /** RegularExpression Id. */
  int _FIELD2 = 45;
  /** RegularExpression Id. */
  int DATE = 46;
  /** RegularExpression Id. */
  int MDATE = 47;
  /** RegularExpression Id. */
  int DAY = 48;
  /** RegularExpression Id. */
  int WEEK = 49;
  /** RegularExpression Id. */
  int MONTH = 50;
  /** RegularExpression Id. */
  int YEAR = 51;
  /** RegularExpression Id. */
  int AFTER = 52;
  /** RegularExpression Id. */
  int BEFORE = 53;
  /** RegularExpression Id. */
  int APPT_START = 54;
  /** RegularExpression Id. */
  int APPT_END = 55;
  /** RegularExpression Id. */
  int CONV_START = 56;
  /** RegularExpression Id. */
  int CONV_END = 57;
  /** RegularExpression Id. */
  int SIZE = 58;
  /** RegularExpression Id. */
  int BIGGER = 59;
  /** RegularExpression Id. */
  int SMALLER = 60;
  /** RegularExpression Id. */
  int CONV = 61;
  /** RegularExpression Id. */
  int CONV_COUNT = 62;
  /** RegularExpression Id. */
  int CONV_MINM = 63;
  /** RegularExpression Id. */
  int CONV_MAXM = 64;
  /** RegularExpression Id. */
  int MODSEQ = 65;
  /** RegularExpression Id. */
  int PRIORITY = 66;
  /** RegularExpression Id. */
  int IS = 67;
  /** RegularExpression Id. */
  int INID = 68;
  /** RegularExpression Id. */
  int UNDERID = 69;
  /** RegularExpression Id. */
  int HAS = 70;
  /** RegularExpression Id. */
  int TYPE = 71;
  /** RegularExpression Id. */
  int ATTACHMENT = 72;
  /** RegularExpression Id. */
  int ITEM = 73;
  /** RegularExpression Id. */
  int SORTBY = 74;
  /** RegularExpression Id. */
  int SORT = 75;

  /** Lexical state. */
  int TEXT = 0;
  /** Lexical state. */
  int DEFAULT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"(\"",
    "\")\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "\"+\"",
    "\"-\"",
    "<RANGE>",
    "<TERM>",
    "<_TERM_START_CHAR>",
    "<_TERM_CHAR>",
    "<QUOTED_TERM>",
    "\"\\\\\\\"\"",
    "<BRACED_TERM>",
    "<QUOTED_RANGE_TERM>",
    "\"content:\"",
    "\"subject:\"",
    "\"msgid:\"",
    "\"envto:\"",
    "\"envfrom:\"",
    "\"contact:\"",
    "\"to:\"",
    "\"from:\"",
    "\"cc:\"",
    "\"tofrom:\"",
    "\"tocc:\"",
    "\"fromcc:\"",
    "\"tofromcc:\"",
    "\"fromorsender:\"",
    "\"in:\"",
    "\"under:\"",
    "\"filename:\"",
    "\"tag:\"",
    "\"message:\"",
    "\"my:\"",
    "\"author:\"",
    "\"title:\"",
    "\"keywords:\"",
    "\"company:\"",
    "\"metadata:\"",
    "<FIELD>",
    "<_FIELD1>",
    "<_FIELD2>",
    "\"date:\"",
    "\"mdate:\"",
    "\"day:\"",
    "\"week:\"",
    "\"month:\"",
    "\"year:\"",
    "\"after:\"",
    "\"before:\"",
    "\"appt-start:\"",
    "\"appt-end:\"",
    "\"conv-start:\"",
    "\"conv-end:\"",
    "\"size:\"",
    "<BIGGER>",
    "\"smaller:\"",
    "\"conv:\"",
    "\"conv-count:\"",
    "\"conv-minm:\"",
    "\"conv-maxm:\"",
    "\"modseq:\"",
    "\"priority:\"",
    "\"is:\"",
    "\"inid:\"",
    "\"underid:\"",
    "\"has:\"",
    "\"type:\"",
    "\"attachment:\"",
    "\"item:\"",
    "\"sortby:\"",
    "\"sort:\"",
    "\"\\r\"",
  };

}
