name: Java Code Quality

on: [pull_request]

jobs:
  check-style:
    name: check-style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: run-checkstyle
        uses: dbelyaev/action-checkstyle@b660daa6be4120416b16213522e673c5b1fd772c # v2.1.0
        with:
          reporter: github-pr-review
          checkstyle_version: "9.3"
          level: error
          fail_level: error
          filter_mode: added
          checkstyle_config: checkstyle-config/config/checkstyle/checkstyle.xml
